# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
# Docs: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Weekly PR for all minor & patch bumps
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "packages/backend"
      - "packages/electron"
      - "packages/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      minor-patch:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - "major"

  # Monthly PRs for major bumps (one PR per package)
  # - package-ecosystem: "npm"
  #   directories:
  #     - "/"
  #     - "packages/backend"
  #     - "packages/electron"
  #     - "packages/frontend"
  #   schedule:
  #     interval: "monthly"
  #   open-pull-requests-limit: 5
  #   ignore:
  #     - dependency-name: "*"
  #       update-types:
  #         - "minor"
  #         - "patch"
