# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
# Docs: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "packages/backend"
      - "packages/electron"
      - "packages/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    groups:
      minor-patch:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
      major:
        update-types:
          - "major"
        patterns:
          - "*"
