#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'privatefolio'

[build]
  image = 'ghcr.io/privatefolio/privatefolio:latest'

[env]
  PORT = '5555'

[[mounts]]
  source = 'privatefolio-data'
  destination = '/app/data'

[http_service]
  internal_port = 5555
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  size = 'shared-cpu-2x'
  memory = "512mb"
