name: 🐛 Bug report
description: Something is not working?
labels: [bug]
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: textarea
    id: steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.

  - type: checkboxes
    id: apps
    attributes:
      label: Apps affected
      options:
        - label: Web app
        - label: Mac desktop app
        - label: Windows desktop app
        - label: Linux desktop app

  - type: checkboxes
    id: browser
    attributes:
      label: Browser (if applicable)
      options:
        - label: Chrome
        - label: Firefox
        - label: Safari
        - label: Other: Brave

  - type: checkboxes
    id: os
    attributes:
      label: Operating system
      options:
        - label: Windows
        - label: Mac with Arm CPU
        - label: Mac with Intel CPU
        - label: Linux

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
