// https://api.etherscan.io/v2/chainlist
export const SUPPORTED_PLATFORMS = [
  "c/ethereum",
  "c/abstract",
  "c/apechain",
  "c/arbitrum-nova",
  "c/arbitrum-one",
  "c/avalanche",
  "c/base",
  "c/berachain",
  "c/bittorrent",
  "c/blast",
  "c/binance-smart-chain",
  "c/celo",
  "c/cronos",
  "c/fraxtal",
  "c/xdai",
  "c/linea",
  "c/mantle",
  "c/memecore",
  "c/moonbeam",
  "c/moonriver",
  "c/optimistic-ethereum",
  "c/polygon-pos",
  "c/polygon-zkevm",
  "c/scroll",
  "c/sonic",
  "c/sophon",
  "c/swellchain",
  "c/taiko",
  "c/unichain",
  "c/wemix-network",
  "c/world-chain",
  "c/xai",
  "c/xdc-network",
  "c/zksync",
  "c/opbnb",
]

export const ETHERSCAN_API_KEY_V2 = "3JHR8S44XRG5VAN774EGSBY175A1QE2EZA"
