name: Continuous Integration

on:
  push:
    branches: ["*"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and cache node_modules
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "yarn"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build
        if: always()

      - name: Lint
        run: yarn lint
        if: always()

      - name: Check types
        run: yarn check-types
        if: always()

      - name: Test
        run: yarn test:ci
        if: always()
