name: Publish Backend

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]

permissions:
    contents: read
    packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  VITE_POSTHOG_KEY: ${{ secrets.VITE_POSTHOG_KEY }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://ghcr.io/privatefolio/privatefolio
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # Create tags for:
          # - latest if it's a push to main
          # - git tag if it's a tagged release
          # - short SHA for any build
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=,format=short

      - name: Build image
        run: yarn docker:build

      - name: Push all tags
        shell: bash
        run: |
          # stash the (newline- or space-separated) tags into one var
          tags="${{ steps.meta.outputs.tags }}"
          echo "Will push these tags:"
          echo "$tags"

          for tag in $tags; do
            echo "Tagging local image as $tag"
            docker tag privatefolio:latest "$tag"
            echo "Pushing $tag"
            docker push "$tag"
          done

      - name: Notify Discord on success
        if: success()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_DEPLOYMENTS_WEBHOOK }}
          status: "Success"
          title: "Privatefolio - Publish Image Succeeded"
          description: |
            **Branch**: `${{ github.ref_name }}`
            **Commit**: `${{ github.sha }}`
          color: 0x00FF00 

      - name: Notify Discord on failure
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_DEPLOYMENTS_WEBHOOK }}
          status: "Failure"
          title: "Privatefolio - Publish Image Failed"
          description: |
            **Branch**: `${{ github.ref_name }}`
            **Commit**: `${{ github.sha }}`
          color: 0xFF0000
