name: Publish Apps

on:
  push:
    tags: [ "*" ]

  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

permissions:
  contents: write

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-publish:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    environment:
      name: production
      url: https://github.com/privatefolio/privatefolio/releases/tag/${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Cache yarn downloads
        uses: actions/cache@v4
        with:
          path: ~/.cache/yarn/v6
          key: yarn-cache-${{ runner.os }}-${{ hashFiles('./yarn.lock') }}
          restore-keys: yarn-cache-${{ runner.os }}-

      - name: Cache node_modules (root)
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: deps-root-${{ runner.os }}-${{ hashFiles('./yarn.lock') }}
          restore-keys: deps-root-${{ runner.os }}-

      - name: Cache node_modules (packages)
        uses: actions/cache@v4
        with:
          path: ./packages/**/node_modules
          key: deps-packages-${{ runner.os }}-${{ hashFiles('./yarn.lock') }}
          restore-keys: deps-packages-${{ runner.os }}-

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo dpkg --add-architecture i386
          wget -nc https://dl.winehq.org/wine-builds/winehq.key
          sudo apt-key add winehq.key
          sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ jammy main'
          sudo apt update
          sudo apt install -y --install-recommends winehq-stable
          sudo apt install -y mono-complete
          sudo snap install snapcraft --classic
          wine64 --version
          mono --version
          snapcraft --version
          yarn install --frozen-lockfile

      - name: Build and Publish Binary (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: yarn build-bin:linux

      - name: Publish Snap
        if: matrix.os == 'ubuntu-latest'
        run: snapcraft upload --release=stable "$(realpath ./packages/electron/out/*.snap)"
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}

      - name: Build and Publish Binary (Windows)
        if: matrix.os == 'ubuntu-latest'
        run: yarn build-bin:win

      - name: Install Dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: yarn install --frozen-lockfile

      # - name: Create temp keychain & import cert
      #   if: matrix.os == 'macos-latest'
      #   run: |
      #     # create & unlock temp keychain
      #     security create-keychain -p temp-pass build.keychain
      #     security default-keychain -s build.keychain
      #     security unlock-keychain -p temp-pass build.keychain
      #     security list-keychains -d user -s build.keychain
      #     security set-keychain-settings -lut 7200 build.keychain

      #     # decode and import p12; -A gives non-interactive access
      #     echo "$CSC_LINK" | base64 --decode > /tmp/cert.p12
      #     security import /tmp/cert.p12 \
      #       -k build.keychain -f pkcs12 -P "$CSC_KEY_PASSWORD" \
      #       -A -T /usr/bin/codesign -T /usr/bin/productsign

      #     # grant key-partition access (include codesign)
      #     security set-key-partition-list \
      #       -S apple-tool:,apple:,codesign -s -k temp-pass build.keychain

      #     # quick sanity check - fails fast if cert unusable
      #     security find-identity -v -p codesigning build.keychain

      #     echo "CSC_KEYCHAIN=build.keychain" >> $GITHUB_ENV
      #   env:
          # CSC_LINK: ${{ secrets.CSC_LINK }}
          # CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

      - name: Build and Publish Binary (macOS)
        if: matrix.os == 'macos-latest'
        run: yarn build-bin:mac
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
        # env:
        #   APPLE_ID: ${{ secrets.APPLE_ID }}
        #   APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        #   APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}

      - name: Notify Discord on success
        if: success()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_DEPLOYMENTS_WEBHOOK }}
          status: "Success"
          title: "Privatefolio - Publish Apps Succeeded"
          description: |
            **Branch**: `${{ github.ref_name }}`
            **Commit**: `${{ github.sha }}`
          color: 0x00FF00

      - name: Notify Discord on failure
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_DEPLOYMENTS_WEBHOOK }}
          status: "Failure"
          title: "Privatefolio - Publish Apps Failed"
          description: |
            **Branch**: `${{ github.ref_name }}`
            **Commit**: `${{ github.sha }}`
          color: 0xFF0000
