name: Release

on:
  push:
    tags: ["*"]

permissions:
  contents: write

env:
  VITE_POSTHOG_KEY: ${{ secrets.VITE_POSTHOG_KEY }}

jobs:
  build-and-release:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'

      # TODO: electron scripts need to be migrated to Bun
      # - name: Setup Bun
      #   uses: oven-sh/setup-bun@v2

      - name: Install Dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo dpkg --add-architecture i386
          wget -nc https://dl.winehq.org/wine-builds/winehq.key
          sudo apt-key add winehq.key
          sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ jammy main'
          sudo apt update
          sudo apt install -y --install-recommends winehq-stable
          sudo apt install -y mono-complete
          wine64 --version
          mono --version
          yarn

      - name: Install Dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: yarn

      - name: Build Binaries (Linux + Windows)
        if: matrix.os == 'ubuntu-latest'
        run: |
          yarn build-bin:linux
          yarn build-bin:win
      
      - name: Build Binary (macOS)
        if: matrix.os == 'macos-latest'
        run: yarn build-bin:mac

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.os }}
          path: packages/electron/out/make/**
          retention-days: 1

  create-release:
    needs: build-and-release
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Display structure of downloaded files
        run: ls -R artifacts
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
